services:
  - type: web
    name: preifma-api-v2
    runtime: docker
    dockerfilePath: ./Dockerfile
    healthCheckPath: /up
    envVars:
      - key: RAILS_ENV
        value: production
      - key: RAILS_LOG_TO_STDOUT
        value: "true"
      - key: RAILS_MASTER_KEY
        sync: false
