production:
  daily_offensive_reset:
    class: DailyOffensiveResetJob
    queue: default
    schedule: at 00:00 every day

development:
  daily_offensive_reset:
    class: DailyOffensiveResetJob
    queue: default
    schedule: at 00:00 every day

test:
  daily_offensive_reset:
    class: DailyOffensiveResetJob
    queue: default
    schedule: at 00:00 every day
